// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_Datatype_allownull_isoutexport1_billTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_Datatype_allownull_isoutexport1_billTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202112300526190_change_Datatype_allownull_isoutexport1_billTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
