// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MergeBranches_ManageLeave : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeBranches_ManageLeave));
        
        string IMigrationMetadata.Id
        {
            get { return "202111240925015_MergeBranches_ManageLeave"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
