// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcol_Reg_Renewdate_tblservicerequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcol_Reg_Renewdate_tblservicerequest));
        
        string IMigrationMetadata.Id
        {
            get { return "202111240602516_addcol_Reg_Renewdate_tblservicerequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
