// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class table_client_migration_issue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_client_migration_issue));
        
        string IMigrationMetadata.Id
        {
            get { return "202112090936372_table_client_migration_issue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
