// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Changes_tbl_User_Story_ColumnSetNullabe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changes_tbl_User_Story_ColumnSetNullabe));
        
        string IMigrationMetadata.Id
        {
            get { return "202112061048525_Changes_tbl_User_Story_ColumnSetNullabe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
