// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_New_Column_UserStoryId_Timesheet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_New_Column_UserStoryId_Timesheet));
        
        string IMigrationMetadata.Id
        {
            get { return "202112061234481_Added_New_Column_UserStoryId_Timesheet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
