// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_datatype_of_totalhours_todecimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_datatype_of_totalhours_todecimal));
        
        string IMigrationMetadata.Id
        {
            get { return "202112150537425_change_datatype_of_totalhours_todecimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
