// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class priority_field_added_in_projecttbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(priority_field_added_in_projecttbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202201251129400_priority_field_added_in_projecttbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
