// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class col_added_databasespace_in_manageservice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(col_added_databasespace_in_manageservice));
        
        string IMigrationMetadata.Id
        {
            get { return "202206231231253_col_added_databasespace_in_manageservice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
