// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addCol_TargetAmount_Employee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCol_TargetAmount_Employee));
        
        string IMigrationMetadata.Id
        {
            get { return "202201180648036_addCol_TargetAmount_Employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
