// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addtbl_BulkMaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtbl_BulkMaster));
        
        string IMigrationMetadata.Id
        {
            get { return "202203021138423_addtbl_BulkMaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
