// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tblExpense_sub_categoey_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblExpense_sub_categoey_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202202070857064_tblExpense_sub_categoey_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
