// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_col_InvoiceNote_in_ServiceRequestHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_col_InvoiceNote_in_ServiceRequestHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202211021209597_add_col_InvoiceNote_in_ServiceRequestHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
