// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_requirefld_EnddtTeamEnd_Project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_requirefld_EnddtTeamEnd_Project));
        
        string IMigrationMetadata.Id
        {
            get { return "202201201234203_remove_requirefld_EnddtTeamEnd_Project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
