// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_clientaddresstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_clientaddresstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202201100847126_add_clientaddresstable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
