// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tblexpensecategory_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblexpensecategory_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202202070850304_tblexpensecategory_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
