// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class categoryid_added_tblsubcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryid_added_tblsubcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202202080513471_categoryid_added_tblsubcategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
