// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_twotbl_DocumentMaster_DocumentChild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_twotbl_DocumentMaster_DocumentChild));
        
        string IMigrationMetadata.Id
        {
            get { return "202206010900508_add_twotbl_DocumentMaster_DocumentChild"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
