// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_Col_Followuptypeid_in_tbl_OpportunityFollowUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Col_Followuptypeid_in_tbl_OpportunityFollowUp));
        
        string IMigrationMetadata.Id
        {
            get { return "202306230839358_add_Col_Followuptypeid_in_tbl_OpportunityFollowUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
