// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modify_tbl_Opportunity_add_Col_BeneficiaryCompanyId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_tbl_Opportunity_add_Col_BeneficiaryCompanyId));
        
        string IMigrationMetadata.Id
        {
            get { return "202306211037575_modify_tbl_Opportunity_add_Col_BeneficiaryCompanyId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
