// <auto-generated />
namespace AbpProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_new_column_exchangerate_bill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_new_column_exchangerate_bill));
        
        string IMigrationMetadata.Id
        {
            get { return "202303100831531_added_new_column_exchangerate_bill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
